### ISSUE TITLE
Add endpoint support for S3 api compatible services

### ISSUE THREAD

**Issue by timureh** [sethkor/s3kor#19]
For example like [here](https://github.com/peak/s5cmd#google-cloud-storage-support)

**Comment by marcosdiez** [comment]
Hi,

I just implemented this feature. 

Fell free to use it :)

https://github.com/marcosdiez/s3kor/releases

**Comment by timureh** [comment]
> Hi,
> 
> I just implemented this feature.
> 
> Fell free to use it :)
> 
> https://github.com/marcosdiez/s3kor/releases

thanks!
respect to you !

**Comment by marcosdiez** [comment]
Thank you for the kind words, but please keep the PR open until it gets merged!
